#Database properties:
db.system: dameng
db.driver: dm.jdbc.driver.DmDriver

instances:
  - db.address: 9.46.118.22
    db.port: 5236
    db.username: SYSDBA
    db.password: VXMzcnBhODgq
    db.connection.url: jdbc:dm://9.46.118.22:5236
    db.name: myDB1

    #Data collector properties:
    poll.interval: 30
    callback.interval: 20
    otel.backend.url: http://localhost:4317
    #otel.backend.using.http: true
    #otel.backend.url: https://host.docker.internal:8991/v1/metrics
    #otel.backend.url: http://localhost:4318/v1/metrics

    #OTel properties:
    otel.service.name: DamengDcA

  - db.address: 9.46.118.22
    db.port: 5236
    db.username: SYSDBA
    db.password: VXMzcnBhODgq
    db.connection.url: jdbc:dm://9.46.118.22:5236
    db.name: myDB2

    #Data collector properties:
    poll.interval: 30
    callback.interval: 20
    otel.backend.url: http://localhost:4317
    #otel.backend.using.http: true
    #otel.backend.url: https://host.docker.internal:8991/v1/metrics
    #otel.backend.url: http://localhost:8992/v1/metrics

    #OTel properties:
    otel.service.name: DamengDcB
