db.system: informix
db.driver: com.informix.jdbc.IfxDriver

instances:
  - db.address: 9.46.251.113
    db.port: 9088
    db.serverName: ol_informix1410
    db.username: USER
    db.password: Base64_Encoded_Password
    db.name: TestInformixDB
    #OTel properties:
    otel.service.name: InformixDB
    #Data collector properties:
    poll.interval: 30
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317
    #Custom Input
    custom.input:
      db.names: 'testDb1, testDb2, testDb3' # Provide the DB Names in Comma separated way

