db.system: informix
db.driver: com.informix.jdbc.IfxDriver

instances:
  - db.address: 9.46.251.113
    db.port: 9088
    db.serverName: ol_informix1410
    db.username: informix
    db.password: cGFzc3dvcmQ=
    db.name: TestInformixDB
    #OTel properties:
    otel.service.name: InformixDB
    #Data collector properties:
   # poll.interval: 30
    custom.poll.interval:
      high: 10 #polling_value_in_sec
      medium: 120 #polling_value_in_sec
      low: 30 #polling_value_in_sec
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317
    #Custom Input
    custom.input:
      db.names: 'testDb1, testDb2, testDb3' # Provide the DB Names in Comma separated way

