db.system: informix
db.driver: com.informix.jdbc.IfxDriver

instances:
#  - db.address: 9.37.231.15 #IP Address
#    db.port: 9088 #Port on which DB is running
#    db.serverName: ol_informix1410
#    db.username: informix
#    db.password: cGFzc3dvcmQ=
#    db.name: vivek
#    db.path: /opt/IBM/Informix_Software_Bundle
#
#    #OTel properties:
#    otel.service.name: InformixDB
#
#      #Data collector properties:
#    #Either use `poll.interval` or `custom.poll.interval`
#    poll.interval: 30
#    #All three category value is Mandatory if leveraging Custom Poll Rate
#    custom.poll.interval:
#      high: 300 #polling_value_in_sec
#      medium: 45 #polling_value_in_sec
#      low: 20 #polling_value_in_sec
#    callback.interval: 20
#    otel.backend.url: http://127.0.0.1:4317
#
#    #Custom Input
#    custom.input:
#      #Time Frame for which you want to get the expensive query. Default value 900 Sec
#      db.sql.elapsed.timeframe: 900   # Values should be in Seconds
#      db.sequential.scan.count: 0


  - db.address: 9.46.251.113 #IP Address
    db.port: 9088 #Port on which DB is running
    db.serverName: ol_informix1410
    db.username: root
    db.password: SGFwcHlAZnlyZUBuZWhhMjAyMQ==
    db.name: instana
    db.path: /opt/IBM/Informix_Software_Bundle

    #OTel properties:
    otel.service.name: InformixDB

    #Data collector properties:
    #Either use `poll.interval` or `custom.poll.interval`
    poll.interval: 30
    #All three category value is Mandatory if leveraging Custom Poll Rate
    custom.poll.interval:
      high: 300 #polling_value_in_sec
      medium: 45 #polling_value_in_sec
      low: 20 #polling_value_in_sec
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317

    #Custom Input
    custom.input:
      #Time Frame for which you want to get the expensive query. Default value 900 Sec
      db.sql.elapsed.timeframe: 900   # Values should be in Seconds
      db.sequential.scan.count: 0
