db.system: informix
db.driver: com.informix.jdbc.IfxDriver

instances:
  - db.address: xxx.xxx.xxx.xxx #IP Address
    db.port: 9088 #Port on which DB is running
    db.serverName: ol_informix1410
    db.username: Informix_User_Name
    db.password: BASE64_Encoded_Password
    db.name: InformixDB
    db.path: /opt/IBM/Informix_Software_Bundle

    #OTel properties:
    otel.service.name: InformixDB

    #Data collector properties:
    #Either use `poll.interval` or `custom.poll.interval`
    poll.interval: 30
    #All three category value is Mandatory if leveraging Custom Poll Rate
    custom.poll.interval:
      high: 300 #polling_value_in_sec
      medium: 45 #polling_value_in_sec
      low: 20 #polling_value_in_sec
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317

    #Custom Input
    custom.input:
      #Time Frame for which you want to get the expensive query. Default value 900 Sec
      db.sql.elapsed.timeframe: 900   # Values should be in Seconds