host.system: simp_host

instances:
  - poll.interval: 30
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317
    #otel.backend.using.http: true
    #otel.backend.url: http://127.0.0.1:4318/v1/metrics
