llm.platform: watsonx
llm.application: llm-dc
server.address: bam-api.res.ibm.com
server.port: 443
server.scheme: https

instances:
  - otel.backend.url: http://localhost:4317
    otel.service.name: WatsonxDC
